### PR TITLE
Added Delete Button in Slideshow

### PR DESCRIPTION
**Pull request by manishbisht**
Fixes: #649 

Licence: AGPL
### Tested on
- [x] Google Chrome
### Reviewers

@oparoz @tempico

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks for the updated PR. Looks like this one is ready for review :). I'll keep you posted.

Also, @imjalpreet could take a look when taking a break from his app :)

**Comment by imjalpreet** [comment]
@oparoz Sure, I will have a look as soon as possible.

**Comment by oparoz** [comment]
@tempico Did you test this?

**Comment by tempico** [comment]
@oparoz,
Yes. I tested few days ago but got OC code integrity check errors and white page while trying to access gallery. So I just reverted gallery version to official one.

tested master branch of https://github.com/manishbisht/gallery.git

**Comment by oparoz** [comment]
@tempico Were you testing on ownCloud master or 9.0?

**Comment by tempico** [comment]
@oparoz, 
9.0.2

**Comment by oparoz** [comment]
@tempico Thanks. Maybe things have changed and master doesn't install on 9.0 any more.

**Comment by tempico** [comment]
@oparoz,
That's bad

**Comment by oparoz** [comment]
@tempico Not really, stable9 is the branch for 9.0, master is for the next release, so if you want to test on 9.1, you should download one of the VMs and install this PR on it. It should then work. I say should because up until now core was a moving target, so it could be that Gallery requires some adjustments if there have been significant changes in an API.

**Comment by tempico** [comment]
@oparoz,
@manishbisht committed changes to master branch of his fork. My idea was to perform regression test of new changes on clone of my owncloud VM (ubuntu 14.04 | nginx+lua + php-fpm + mysql + redis + hetzner storage box via SMB). ¯_(ツ)_/¯
If new functionality works for you, I will try to diff changes from master and patch my staging environment.

**Comment by oparoz** [comment]
@tempico - Applying [this patch](https://patch-diff.githubusercontent.com/raw/owncloud/gallery/pull/658.patch) to your clone should provide the functionality.

**Comment by manishbisht** [comment]
@tempico Are you now able to use the functionality after applying the patch.

**Comment by tempico** [comment]
@manishbisht,

>  slideshowcontrols.js:435 
> TypeError: Gallery.utility.getWebdavRoot is not a function. (In 'Gallery.utility.getWebdavRoot()', 'Gallery.utility.getWebdavRoot' is undefined)

**Comment by manishbisht** [comment]
@tempico Try changing that line with `url:OC.getRootPath()+'/remote.php/webdav/'+imagePath,` or `url: Gallery.Utility.getWebdavRoot() + '/' + imagePath,` and let me know if you are able to fix this problem

**Comment by tempico** [comment]
@manishbisht,

> url:OC.getRootPath()+'/remote.php/webdav/'+imagePath,

Works fine in Safari and Chrome! Thanks!

> url: Gallery.Utility.getWebdavRoot() + '/' + imagePath,
> [ Error] TypeError: Gallery.Utility.getWebdavRoot is not a function. (In 'Gallery.Utility.getWebdavRoot()', 
> 'Gallery.Utility.getWebdavRoot' is undefined)
>   _deleteImage (slideshowcontrols.js:435)
>   (anonymous function) (slideshowcontrols.js:44)
>   (anonymous function)
>   dispatch (jquery.min.js:5:14135)
>   handle (jquery.min.js:5:10872)

**Comment by manishbisht** [comment]
@oparoz @tempico is getting error 

> slideshowcontrols.js:435 
> TypeError: Gallery.utility.getWebdavRoot is not a function. (In 'Gallery.utility.getWebdavRoot()', 'Gallery.utility.getWebdavRoot' is undefined)

Are you getting the same error on applying the latest commit because I am not getting this error ?

**Comment by oparoz** [comment]
@manishbisht - That's because @tempico is using 9.0 when this PR only works on 9.1.

**Comment by manishbisht** [comment]
Thanks @oparoz I think its now ready to get merge with owncloud/gallery :)

**Comment by oparoz** [comment]
@manishbisht 
1. You need to squash your commits
2. We need to wait for the stable9.1 branch to be created, mid-July. The feature will probably be part of Gallery+ before that

**Comment by manishbisht** [comment]
@oparoz I have squash all my commits. :) Now waiting for stable9.1 branch

**Comment by oparoz** [comment]
Thank you.

**Comment by oparoz** [comment]
Transferred locally via #676 and will be part of the next release of Gallery+
